[project]
name = "scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthias", email = "matthias@repath.earth" }
]
requires-python = ">=3.13"
dependencies = [
    "prefect>=3.4.1",
    "prefect-cloud>=0.1.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
